# ==================================
#           DO NOT TOUCH!
# ==================================

site_name: Formula Trinity Wiki
site_description: Engineering documentation for Formula Trinity
site_url: https://formula-trinity.github.io/ft-wiki/
# repo_url: https://github.com/Formula-Trinity/ft-wiki

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    # - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# ==================================
#        END OF DO NOT TOUCH...
# ==================================

nav:
  - Home: index.md
  - FTX7:
      - ftx7/index.md
      - Powertrain:
          - ftx7/powertrain/index.md
          - Subsystem 1: ftx7/powertrain/subsystem-01/index.md
      - Drivetrain:
          - ftx7/drivetrain/index.md
          - Subsystem 1: ftx7/drivetrain/subsystem-01/index.md
      - Chassis:
          - ftx7/chassis/index.md
          - Subsystem 1: ftx7/chassis/subsystem-01/index.md
      - Suspension:
          - ftx7/suspension/index.md
          - Subsystem 1: ftx7/suspension/subsystem-01/index.md
      - Aero:
          - ftx7/aero/index.md
          - Subsystem 1: ftx7/aero/subsystem-01/index.md
      - Electronics:
          - ftx7/electronics/index.md
          - Subsystem 1: ftx7/electronics/subsystem-01/index.md
          - Subsystem 2: ftx7/electronics/subsystem-02/index.md
  - Manufacturing:
      - manufacturing/index.md
  - Competition Overview:
      - competition/index.md
      - Static Events:
        - competition/statics/index.md
        - Design Judging:
          - competition/statics/design/index.md
          - Engineering Design Report: competition/statics/design/edr.md
          - Overall Vehicle Concept: competition/statics/design/overall_concept.md
          - Structural Design inc. Suspension & Brakes: competition/statics/design/struct_design.md
          - Powertrain Concept & Choice, Simulation, Design & Analysis: competition/statics/design/pt.md
          - Overall Timing, Manufacturing, Procurement Plan plus Team Organisation Plan: competition/statics/design/timing_planning.md
          - Design for Manufacture & Profit, Customer Respect and Innovation: competition/statics/design/design_for_manufacture.md
        - Cost & Manufacturing Judging: competition/statics/cost/index.md
      - Scrutineering:
        - competition/scrut/index.md
        - Tech: competition/scrut/tech/index.md
        - Safety: competition/scrut/safety/index.md
        - Chassis: competition/scrut/chassis/index.md
        - Tilt: competition/scrut/tilt/index.md
        - Noise: competition/scrut/noise/index.md
        - Brakes: competition/scrut/brakes/index.md
      - Dynamic Events:
        - competition/dynamics/index.md
  - How to Contribute: contributing.md